### ISSUE TITLE
Question regarding tests

### ISSUE THREAD

**Issue by jbi35** [T4mmi/ITKBinaryThinning3D#4]
Hi T4mmi,
I am interested in using your BinaryThinning3D filter for a segmentation project. So as a first step, I wanted to try the filter on the test data you provided (test/Data/input.tif). 

To do so I followed the following steps:
1. I created a new conda environment:
```conda create -n test_thinning python=3.6```
```source activate test_thinning```
2. Then I ran the installation instructions you provided
```python -m pip install --upgrade pip```
```python -m pip install itk-binarythinning3d```
3. I cloned this repo, navigated into the ```test``` directory and ran
```python BinaryThinningImageFilter3DTest.py```

The code seems to run just fine and I do not get any error message. However, the resulting output image (test/Data/output.tif) is completely black and does not contain the skeleton of the corresponding input image. Is this the correct behavior? From looking at the code in ```BinaryThinningImageFilter3DTest.py``` I would have assumed that the output image should contain the skeleton. I've tried the procedure above on both a macOS and a CentOS system with the same result.

**Comment by T4mmi** [comment]
Hi @jbi35,
thanks for your interest in this module !

Your test workflow is correct and if the test runs without errors it should return a skeleton image as `output.tif` ... my first question would be :
> how did you check the output image ?

`output.tif` is a pseudo-indexed binary image stored as `uint8` where background is coded `0` and foreground (skeleton) is coded `1` so if you open it with a 'lambda' image viewer (that display `uint8` images with a 256 colors lookup table) you should indeed observe a 'black' image.

Could you try displaying `output.tif` with a modified lookup table (using some tools like [Slicer 3D](https://www.slicer.org/) or [Paraview](https://www.paraview.org/)). Or in a pythonic way, check the min/max values for `output.tif` (require `imageio` or equivalent, `numpy` and possibly `ipython`):
```
import imageio  # you could use PIL or PILLOW as well
output= imageio.volread('Data/output.tif')

import numpy
min, max = (numpy.min(output), numpy.max(output))
print('min : {}, max : {}'.format(min, max))
```
If this code return  `min : 0, max : 1` then it means the test completed successfully (at least as expected, does not insure the skeleton is exact, just that it exists). The issue is then with the coding/display of the output.


Keep me posted of your findings, if this solved the issue I'll add the solution to the README for other users

;)

**Comment by jbi35** [comment]
Hi @T4mmi,

thanks for your help. It was indeed my fault, as I assumed that the skeleton would also appear white in the output. Looking at the image in Paraview resolved this. I also already tried the code on an actual airways segmentation, works like charm :-)

 Thanks again

**Comment by T4mmi** [comment]
Glad I could help :-)
I will update the README and test to explicit the output coding.
